# Generated by Django 6.0 on 2025-12-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.PositiveIntegerField()),
                ('img', models.ImageField(blank=True, null=True, unique=True, upload_to='identifiers/')),
                ('value', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='identifier.typeid')),
            ],
        ),
    ]
